FROM ubuntu:latest as python
COPY ./Python/requirements.txt /requirements
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python3 python3-pip
RUN pip install --break-system-packages -r /requirements.txt

FROM python as app
ENV FLASK_ENV=development
COPY ./Python /app
ENTRYPOINT [ "python3", "/app/ApiUpload.py" ]