services:
  wad-server:
    image: dockermex:nginx-alpine
    container_name: dockermex-frontend
    build:
      context: Dockermex_Frontend
      dockerfile: Dockerfile
    env_file:
      - ".env"
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads:ro
      - ./Dockermex_Frontend/html/daisyfans:/daisyfans:ro
      - ./Dockermex_Frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Dockermex_Frontend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Dockermex_Frontend/nginx/modsecurity:/etc/nginx/modsecurity:ro
      - ./Dockermex_Frontend/html:/usr/share/nginx/html:ro
      - ${SSL_PRIVATE_KEY}:/etc/nginx/ssl/private.key:ro
      - ${SSL_FULLCHAIN_CERT}:/etc/nginx/ssl/fullchain.crt:ro
      - ${SSL_WADS_KEY}:/etc/nginx/ssl/wads.key:ro
      - ${SSL_WADS_CERT}:/etc/nginx/ssl/wads.crt:ro
      - modsec_logs:/var/log/nginx/modsec
    ports: ["443:443", "444:444"]
    depends_on:
      - wad-upload-api
    networks:
      wad-net:
        aliases: ["wads.zerofuchs.local", "master"]

  wad-upload-api:
    image: dockermex:python
    build:
      context: Dockermex_Api
      dockerfile: Dockerfile.Python
    env_file:
      - .env
    container_name: dockermex-api
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads
      - ./Dockermex_Api/Python:/app:ro
      - ./service-configs:/service-configs
      - ./configs:/configs:ro
      - ./sqlite:/sqlite
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_SALT=${DB_SALT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: "1"             
          memory: "128M"          
    networks:
      wad-net:
        aliases:
          - wad-upload-api-server
    restart: unless-stopped

networks:
  wad-net:
    driver: bridge

volumes:
  modsec_logs:
    driver: local

# Notes for non-local registry:
# docker tag nginx:modsec registry.url/nginx:modsec
# docker push registry.url/nginx:modsec
# docker tag dockermex:python registry.url/dockermex:python
# docker push registry.url/dockermex:python