services:
  wad-server:
    image: nginx:alpine
    container_name: wads_nuts
    environment:
      - htpassword=replaceme
    volumes:
      - ./iwads/freeware:/iwads
      - ./pwads:/pwads
      - ./nginx_vol/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./ssl/private.key:/etc/nginx/ssl/private.key
      - ./ssl/fullchain.crt:/etc/nginx/ssl/fullchain.crt
      - ./ssl/private.key:/etc/nginx/ssl/wads.key
      - ./ssl/fullchain.crt:/etc/nginx/ssl/wads.crt
    ports: ["443:443", "444:444"]
    depends_on:
      - wad-upload-api
    entrypoint: |
      sh -c '
      apk add --no-cache apache2-utils
      if [ ! -f /etc/nginx/.htpasswd ]; then
        htpasswd -cb /etc/nginx/.htpasswd admin replaceme
      fi
      nginx -g "daemon off;" &
      wait
      '
    networks:
      wad-net:
        aliases: ["wads.zerofuchs.net", "master"]

  wad-upload-api:
    image: ubuntu:latest
    volumes:
      - ./iwads:/iwads
      - ./pwads:/pwads
      - ./Python:/app
      - ./service-configs:/service-configs
      - ./configs:/configs
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    entrypoint: |
      sh -c '
      pip install -r requirements.txt
      python ApiUpload.py
      '
    deploy:
      resources:
        limits:
          cpus: "1"             
          memory: "128M"          
    networks:
      wad-net:
        aliases:
          - wad-upload-api-server
    restart: unless-stopped

networks:
  wad-net:
    driver: bridge
