services:
  odamex_tiny:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_tiny
    environment:
      - IWAD=freedoom1.wad           # Specify the default IWAD here
      - CONFIGFILE=coop-local.cfg    # Specify the configuration file if needed
      - ODAPORT=10666
    ports:
      - 10666:10666/udp        # Map container UDP port to host
    volumes:
      - ./iwads/freeware:/app/iwads:ro        # Mount host IWADs folder
      - ./pwads/coop:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config:ro     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2"             
          memory: "48M"          
    networks:
      - wad-net
    restart: unless-stopped

  odamex_tiny2:
    build:
      context: .
    image: odamexdocker:alpine
    container_name: odamex_tiny2
    environment:
      - IWAD=DOOM2.WAD         # Specify the default IWAD here
      - CONFIGFILE=coop-local.cfg     # Specify the configuration file if needed
      - ODAPORT=10565
    ports:
      - 10565:10565/udp         # Map container UDP port to host
    volumes:
      - ./iwads/commercial:/app/iwads:ro        # Mount host IWADs folder
      - ./pwads/coop:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config:ro     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2"             
          memory: "48M"          
    networks:
      - wad-net
    restart: unless-stopped

  wad-server:
    image: nginx:alpine
    container_name: wads_server
    environment:
      - htpassword=replaceme
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads:ro
      - ./nginx_vol/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./ssl/private.key:/etc/nginx/ssl/private.key:ro
      - ./ssl/fullchain.crt:/etc/nginx/ssl/fullchain.crt:ro
      - ./ssl/wads.key:/etc/nginx/ssl/wads.key:ro
      - ./ssl/wads.crt:/etc/nginx/ssl/wads.crt:ro
    ports: ["443:443", "444:444"]
    depends_on:
      - wad-upload-api
    entrypoint: |
      sh -c '
      apk add --no-cache apache2-utils
      if [ ! -f /etc/nginx/.htpasswd ]; then
        htpasswd -cb /etc/nginx/.htpasswd admin replaceme
      fi
      nginx -g "daemon off;" &
      wait
      '
    networks:
      wad-net:
        aliases: ["wads.zerofuchs.net", "master"]

  wad-upload-api:
    image: odamex_python:latest
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads
      - ./Python:/app:ro
      - ./service-configs:/service-configs
      - ./configs:/configs:ro
      - ./sqlite:/sqlite
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: "1"             
          memory: "128M"          
    networks:
      wad-net:
        aliases:
          - wad-upload-api-server
    restart: unless-stopped

networks:
  wad-net:
    driver: bridge
