services:
  odamex_duel_freedoom1:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_duel_doom2
    env_file:
      - .env
    environment:
      - IWAD=commercial/DOOM2.WAD
      - CONFIGFILE=dm-modern.cfg
      - ODAPORT=10666
    ports:
      - 10666:10666/udp
    volumes:
      - ${IWAD_FOLDER}:/app/iwads:ro
      - ${PWAD_FOLDER}/stub:/app/pwads:ro
      - ${ODAMEX_CONFIGS_PATH}:/app/config:ro
    deploy:
      resources:
        limits:
          cpus: "${ODAMEX_CPU_LIMIT}"             # Restrict CPU
          memory: "${ODAMEX_MEMORY_LIMIT}"          
    restart: unless-stopped
    networks:
      - wad-net

  odamex_dm_freedm2:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_dm_freedm
    env_file:
      - .env
    environment:
      - IWAD=freeware/freedm.wad
      - CONFIGFILE=dm-modern.cfg
      - ODAPORT=10569
    ports:
      - 10569:10569/udp
    volumes:
      - ${IWAD_FOLDER}:/app/iwads:ro
      - ${PWAD_FOLDER}/dm:/app/pwads:ro
      - ${ODAMEX_CONFIGS_PATH}:/app/config:ro
    deploy:
      resources:
        limits:
          cpus: "${ODAMEX_CPU_LIMIT}"
          memory: "${ODAMEX_MEMORY_LIMIT}"
    restart: unless-stopped
    networks:
      - wad-net

  odamex_coop_freedoom2:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_coop_freedoom2
    env_file:
      - .env
    environment:
      - IWAD=freeware/freedoom2.wad
      - CONFIGFILE=coop-full-throttle.cfg
      - ODAPORT=10571
    ports:
      - 10571:10571/udp
    volumes:
      - ${IWAD_FOLDER}:/app/iwads:ro
      - ${PWAD_FOLDER}/coop:/app/pwads:ro
      - ${ODAMEX_CONFIGS_PATH}:/app/config:ro
    deploy:
      resources:
        limits:
          cpus: "${ODAMEX_CPU_LIMIT}"
          memory: "${ODAMEX_MEMORY_LIMIT}"
    restart: unless-stopped
    networks:
      - wad-net

  odamex_coop_deus_vultII:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_coop_deus_vultII
    env_file:
      - .env
    environment:
      - IWAD=freeware/freedoom2.wad
      - CONFIGFILE=coop-modern.cfg
      - ODAPORT=10572
    ports:
      - 10572:10572/udp
    volumes:
      - ${IWAD_FOLDER}:/app/iwads:ro
      - ${PWAD_FOLDER}/scythe:/app/pwads:ro
      - ${ODAMEX_CONFIGS_PATH}:/app/config:ro
    deploy:
      resources:
        limits:
          cpus: "${ODAMEX_CPU_LIMIT}"
          memory: "${ODAMEX_MEMORY_LIMIT}"
    restart: unless-stopped
    networks:
      - wad-net

networks:
  wad-net:
    driver: bridge

