services:
  odamex_duel_freedoom1:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_duel_freedoom1
    env_file:
      - .env
    environment:
      - IWAD=freedoom1.wad           # Specify the default IWAD here
      - CONFIGFILE=dm-modern.cfg  # Specify the configuration file if needed
      - ODAPORT=10666
    ports:
      - 10666:10666/udp        # Map container UDP port to host
    volumes:
      - ${iWAD_FOLDER}/freeware:/app/iwads:ro        # Mount host IWADs folder
      - ${PWAD_FOLDER}/duel:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2"             # Restrict CPU
          memory: "64M"          
    restart: unless-stopped

  odamex_dm_freedm2:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_dm_freedm
    environment:
      - ODAPORT=10569
      - CONFIGFILE=dm-modern.cfg
    ports:
      - 10569:10569/udp         # Map container UDP port to host
    volumes:
      - ${iWAD_FOLDER}/freeware:/app/iwads/:ro        # Mount host IWADs folder
      - ${PWAD_FOLDER}/dm:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2"             # Restrict CPU
          memory: "64M"          
    restart: unless-stopped  

  odamex_coop_freedoom2:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_coop_freedoom2
    environment:
      - IWAD=freedoom2.wad
      - ODAPORT=10571
      - CONFIGFILE=coop-full-throttle.cfg
    ports:
      - 10571:10571/udp         # Map container UDP port to host
    volumes:
      - ${iWAD_FOLDER}/freeware:/app/iwads:ro        # Mount host IWADs folder
      - ${PWAD_FOLDER}/nil:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2"             # Restrict CPU
          memory: "64M"          
    restart: unless-stopped

  odamex_coop_deus_vultII:
    build:
      context: .
    image: odamex:latest
    container_name: odamex_coop_deus_vultII
    environment:
      - IWAD=freedoom2.wad          # Specify the default IWAD here
      - CONFIGFILE=coop-modern.cfg    # Specify the configuration file if needed
      - ODAPORT=10572
    ports:
      - 10572:10572/udp        # Map container UDP port to host
    volumes:
      - ${iWAD_FOLDER}/freeware:/app/iwads:ro        # Mount host IWADs folder
      - ${PWAD_FOLDER}/scythe:/app/pwads:ro        # Mount host PWADs folder
      - ./configs:/app/config     # Mount config folder for custom configurations
    deploy:
      resources:
        limits:
          cpus: "0.2" 
          memory: "64M"          
    restart: unless-stopped



