services:
  wad-server:
    image: your.docker.registry.com/dockermex/frontend
    container_name: dockermex-frontend
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads:ro
      - ./Dockermex_Frontend/html/daisyfans:/daisyfans:ro
      - ./Dockermex_Frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Dockermex_Frontend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Dockermex_Frontend/nginx/modsecurity:/etc/nginx/modsecurity:ro
      - ./Dockermex_Frontend/html:/usr/share/nginx/html:ro
      - ./Dockermex_Frontend/ssl/private.key:/etc/nginx/ssl/private.key:ro
      - ./Dockermex_Frontend/ssl/fullchain.crt:/etc/nginx/ssl/fullchain.crt:ro
      - ./Dockermex_Frontend/ssl/wads.key:/etc/nginx/ssl/wads.key:ro
      - ./Dockermex_Frontend/ssl/wads.crt:/etc/nginx/ssl/wads.crt:ro
      - modsec_logs:/var/log/nginx/modsec
    ports: ["443:443", "444:444"]
    depends_on:
      - wad-upload-api
    networks:
      wad-net:
        aliases: ["wads.zerofuchs.local", "master"]

  wad-upload-api:
    image: your.docker.registry.com/dockermex/python
    container_name: dockermex-api
    volumes:
      - ./iwads:/iwads:ro
      - ./pwads:/pwads
      - ./Dockermex_Api/Python:/app:ro
      - ./service-configs:/service-configs
      - ./configs:/configs:ro
      - ./sqlite:/sqlite
    security_opt:
      - no-new-privileges:true
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: "1"             
          memory: "128M"          
    networks:
      wad-net:
        aliases:
          - wad-upload-api-server
    restart: unless-stopped

networks:
  wad-net:
    driver: bridge

volumes:
  modsec_logs:
    driver: local